USE [lb1];
GO

CREATE TABLE [dbo].[Holdings] (
    [ACCT_NBR] INT NOT NULL PRIMARY KEY,
    [SYMBOL] NVARCHAR(7) NULL,
    [SHARES] DECIMAL(12, 2) NULL,
    [PUR_PRICE] DECIMAL(6, 2) NULL,
    [PUR_DATE] DATE NULL
);

CREATE TABLE [dbo].[Industry] (
    [IND_CODE] INT NOT NULL PRIMARY KEY,
    [IND_NAME] NVARCHAR(5) NULL,
    [LONG_NAME] NVARCHAR(20) NULL
);