CREATE TABLE [dbo].[Master] (
    [SYMBOL] NVARCHAR(7) NOT NULL PRIMARY KEY,
    [CO_NAME] NVARCHAR(20) NULL,
    [EXCHANGE] NVARCHAR(8) NULL,
    [CUR_PRICE] DECIMAL(7, 3) NULL,
    [YRL_HIGH] DECIMAL(7, 3) NULL,
    [YRL_LOW] DECIMAL(7, 3) NULL,
    [P_E_RATIO] DECIMAL(7, 2) NULL,
    [BETA] DECIMAL(4, 2) NULL,
    [PROJ_GRTH] INT NULL,
    [INDUSTRY] INT NULL,
    [PRICE_CHG] INT NULL,
    [SAFETY] INT NULL,
    [RATING] NVARCHAR(4) NULL,
    [RANK] DECIMAL(4, 2) NULL,
    [OUTLOOK] INT NULL,
    [RCMNDATION] NVARCHAR(5) NULL,
    [RISK] NVARCHAR(4) NULL
)